### ISSUE TITLE
Crash on Cyanogenmod 4.3

### ISSUE THREAD

**Issue by davidgyoung** [RadiusNetworks/proximitykit-reference-android#10]
The crash happens on startup with the branch testing-geofences-v5.  It looks like we need to check if the PendingIntent is null, which it apparently is in this case.

E/AndroidRuntime( 3170): FATAL EXCEPTION: main
E/AndroidRuntime( 3170): java.lang.RuntimeException: Unable to create application com.radiusnetworks.androidproximitykitreference.AndroidProximityKitReferenceApplication: java.lang.NullPointerException
E/AndroidRuntime( 3170): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4633)
E/AndroidRuntime( 3170): 	at android.app.ActivityThread.access$1300(ActivityThread.java:153)
E/AndroidRuntime( 3170): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
E/AndroidRuntime( 3170): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3170): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 3170): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime( 3170): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3170): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 3170): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
E/AndroidRuntime( 3170): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
E/AndroidRuntime( 3170): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3170): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 3170): 	at com.radiusnetworks.androidproximitykitreference.AndroidProximityKitReferenceApplication.servicesConnected(AndroidProximityKitReferenceApplication.java:215)
E/AndroidRuntime( 3170): 	at com.radiusnetworks.androidproximitykitreference.AndroidProximityKitReferenceApplication.onCreate(AndroidProximityKitReferenceApplication.java:126)
E/AndroidRuntime( 3170): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 3170): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4630)
E/AndroidRuntime( 3170): 	... 10 more

**Comment by mattwritescode** [comment]
Oh Android you feisty little devil.

**Comment by mattwritescode** [comment]
ok I put in a NullPointerException catch. give it a try when you get a chance.

**Comment by davidgyoung** [comment]
As of this change, I get:

E/AndroidRuntime( 5257): java.lang.RuntimeException: Unable to create application com.radiusnetworks.androidproximitykitreference.AndroidProximityKitReferenceApplication: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
E/AndroidRuntime( 5257): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4633)
E/AndroidRuntime( 5257): 	at android.app.ActivityThread.access$1300(ActivityThread.java:153)
E/AndroidRuntime( 5257): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
E/AndroidRuntime( 5257): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5257): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 5257): 	at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime( 5257): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5257): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 5257): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
E/AndroidRuntime( 5257): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
E/AndroidRuntime( 5257): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5257): Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
E/AndroidRuntime( 5257): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:563)
E/AndroidRuntime( 5257): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:269)
E/AndroidRuntime( 5257): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/AndroidRuntime( 5257): 	at android.app.Dialog.show(Dialog.java:281)
E/AndroidRuntime( 5257): 	at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
E/AndroidRuntime( 5257): 	at com.radiusnetworks.androidproximitykitreference.AndroidProximityKitReferenceApplication.servicesConnected(AndroidProximityKitReferenceApplication.java:224)
E/AndroidRuntime( 5257): 	at com.radiusnetworks.androidproximitykitreference.AndroidProximityKitReferenceApplication.onCreate(AndroidProximityKitReferenceApplication.java:127)
E/AndroidRuntime( 5257): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
E/AndroidRuntime( 5257): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4630)
E/AndroidRuntime( 5257): 	... 10 more

**Comment by mattwritescode** [comment]
Ok, I've put in yet another layer of error dialogs in case one fails, and the next fails. and the next. Give it another try. If this fails. I'm just going to catch the exception and log an error, nothing else.

**Comment by davidgyoung** [comment]
Dialog is displayed properly as of 6748ea1749d7963ca6edac9a2e4d30549bb1099f

**Comment by cupakromer** [comment]
Closing with the recent release.
